# ============================================================================
# Global local ancestry (GLA) shrinkage helpers -- NOT used by ancestry_split()
# ============================================================================
#
# ancestry_split() shrinks ambiguous splits toward 1/2, not toward GLA: in
# the chr19 simulations the true AFR share of mixed-het alleles was ~0.50,
# while GLA (~0.82) measures how common AFR haplotypes are in the cohort,
# which does not decide which of a mixed het's two haplotypes carries the
# allele. These internal helpers are kept only so the simulation scripts
# (simulation/00_prep_*.R, simulation/gla_vs_half/) can rebuild the GLA arm
# of the GLA-vs-1/2 comparison.
#
# When a variant's alt allele is carried almost exclusively by ambiguous
# mixed-ancestry heterozygotes, the per-variant p1/p2 (or p[k]) ancestry
# split ratio is poorly estimated from that variant alone -- in the extreme
# (singleton) case it is entirely undetermined and previously defaulted to
# 0.5/0.5. These helpers compute a per-chromosome-arm "global local ancestry"
# (GLA) proportion, from the MSP ancestry tracts directly (not from
# genotypes, and without using haplotype phase -- i.e. the same unphased
# diploid ancestry codes 1..K/mixed that the per-variant estimator itself
# uses), to use as a shrinkage target: the less informative a variant's own
# evidence, the more its split ratio is pulled toward its arm's GLA.
#
# `centromeres_hg38` (chrom, p_end, q_start) is internal package data
# (R/sysdata.rda), generated by inst/scripts/centromeres_hg38.R from UCSC's hg38
# "centromeres" track. Autosomes only (chr1-chr22).

#' Assign each position to a chromosome arm using the hg38 centromere table
#'
#' @param chrom Character vector of chromosome names (with or without "chr").
#' @param pos Integer/numeric vector of positions, same length as \code{chrom}.
#' @return Integer vector (0 = p-arm, 1 = q-arm), same length as \code{pos}.
#'   Positions inside the centromeric gap itself (extremely rare -- centromeres
#'   are largely inaccessible to short-read variant calling) are assigned to
#'   the q-arm as a pragmatic tie-break.
#' @keywords internal
.assign_arm <- function(chrom, pos) {
  chrom_clean <- sub("^chr", "", as.character(chrom))
  idx <- match(chrom_clean, sub("^chr", "", centromeres_hg38$chrom))
  if (anyNA(idx))
    stop("GLA shrinkage only supports autosomal hg38 chromosomes (chr1-chr22); got: ",
         paste(unique(chrom_clean[is.na(idx)]), collapse = ", "))
  p_end <- centromeres_hg38$p_end[idx]
  ifelse(pos < p_end, 0L, 1L)
}

#' Compute per-arm, per-population global local ancestry (GLA) proportions
#'
#' Aggregates the diploid ancestry code (1..K pure, K+1..K+M mixed) of every
#' sample over every MSP tract, length-weighted by tract bp, split into
#' p-arm/q-arm using \code{\link{.assign_arm}}. Falls back to whole-chromosome
#' GLA for an arm with zero informative tracts (e.g. the acrocentric p-arms of
#' chr13/14/15/21/22).
#'
#' @param tract_df data.frame with columns \code{chrom, spos, epos} (as
#'   returned by \code{.parse_msp()}'s \code{tract_df}, already restricted to
#'   the chromosome(s) being processed).
#' @param anc_diploid_tract Integer matrix (samples x tracts) of diploid
#'   ancestry codes, same column order as \code{tract_df} rows.
#' @param pure_codes_named Named integer vector, population name -> diploid
#'   code 1..K (as built in \code{\link{ancestry_split}}).
#' @param mixed_codes_df data.frame(code, pop1, pop2) for all mixed pairs (as
#'   built in \code{\link{ancestry_split}}).
#' @return Named list, one entry per chromosome present in \code{tract_df}
#'   (name = \code{"chr<N>"}), each a 2 x K numeric matrix (rows "p"/"q",
#'   columns = population names) of GLA proportions.
#' @keywords internal
.compute_arm_gla <- function(tract_df, anc_diploid_tract,
                              pure_codes_named, mixed_codes_df) {
  pop_names <- names(pure_codes_named)
  K <- length(pure_codes_named)
  chrom_clean <- sub("^chr", "", tract_df$chrom)
  uniq_chroms <- unique(chrom_clean)

  tract_len <- tract_df$epos - tract_df$spos
  tract_arm <- .assign_arm(tract_df$chrom, tract_df$spos)  # 0 = p, 1 = q

  # Length-weighted (T_pure, T_mixed) totals for a subset of tract columns
  compute_T <- function(tract_idx) {
    if (length(tract_idx) == 0) return(NULL)
    w <- tract_len[tract_idx]
    sub_mat <- anc_diploid_tract[, tract_idx, drop = FALSE]
    T_pure <- vapply(seq_len(K), function(k)
      sum(colSums(sub_mat == k) * w), numeric(1))
    names(T_pure) <- pop_names
    T_mixed <- vapply(seq_len(nrow(mixed_codes_df)), function(m)
      sum(colSums(sub_mat == mixed_codes_df$code[m]) * w), numeric(1))
    list(pure = T_pure, mixed = T_mixed)
  }

  # T -> per-population GLA proportions: (2*T_pure_k + sum of incident mixed
  # T's) / (2 * total length-weighted diploid calls)
  gla_row <- function(tl) {
    if (is.null(tl)) return(NULL)
    total <- sum(tl$pure) + sum(tl$mixed)
    if (total <= 0) return(NULL)
    out <- numeric(K)
    names(out) <- pop_names
    for (p in seq_len(K)) {
      incident <- mixed_codes_df$pop1 == pop_names[p] | mixed_codes_df$pop2 == pop_names[p]
      out[p] <- (2 * tl$pure[p] + sum(tl$mixed[incident])) / (2 * total)
    }
    out
  }

  gla_by_chrom <- list()
  for (cc in uniq_chroms) {
    chrom_keep <- chrom_clean == cc

    gla_p <- gla_row(compute_T(which(chrom_keep & tract_arm == 0L)))
    gla_q <- gla_row(compute_T(which(chrom_keep & tract_arm == 1L)))

    if (is.null(gla_p) || is.null(gla_q)) {
      gla_all <- gla_row(compute_T(which(chrom_keep)))
      if (is.null(gla_all))
        stop("No ancestry-informative tracts found on chrom ", cc,
             " -- cannot compute GLA shrinkage target")
      if (is.null(gla_p)) gla_p <- gla_all
      if (is.null(gla_q)) gla_q <- gla_all
    }

    gla_by_chrom[[paste0("chr", cc)]] <- rbind(p = gla_p, q = gla_q)
  }
  gla_by_chrom
}
